package io.github.entity;
// Generated Jul 2, 2026, 12:12:19 PM by Hibernate Tools 6.5.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Staffs generated by hbm2java
 */
@Entity
@Table(name="staffs"
    ,catalog="sales"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Staffs  implements java.io.Serializable {


     private Integer staffId;
     private Staffs staffs;
     private String firstName;
     private String lastName;
     private String email;
     private String phone;
     private byte active;
     private int storeId;
     private Set staffses = new HashSet(0);

    public Staffs() {
    }

	
    public Staffs(String firstName, String lastName, String email, byte active, int storeId) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.active = active;
        this.storeId = storeId;
    }
    public Staffs(Staffs staffs, String firstName, String lastName, String email, String phone, byte active, int storeId, Set staffses) {
       this.staffs = staffs;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.phone = phone;
       this.active = active;
       this.storeId = storeId;
       this.staffses = staffses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="staff_id", unique=true, nullable=false)
    public Integer getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="manager_id")
    public Staffs getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Staffs staffs) {
        this.staffs = staffs;
    }

    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", unique=true, nullable=false, length=255)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", length=25)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="active", nullable=false)
    public byte getActive() {
        return this.active;
    }
    
    public void setActive(byte active) {
        this.active = active;
    }

    
    @Column(name="store_id", nullable=false)
    public int getStoreId() {
        return this.storeId;
    }
    
    public void setStoreId(int storeId) {
        this.storeId = storeId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="staffs")
    public Set getStaffses() {
        return this.staffses;
    }
    
    public void setStaffses(Set staffses) {
        this.staffses = staffses;
    }




}


