package io.github.generator;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import io.github.config.GeneratorConfig;

/**
 * Membuat file {@code hibernate.properties} sementara secara otomatis
 * dari konfigurasi yang sudah dibaca dari {@code application.properties} /
 * {@code application.yml}.
 *
 * <p>File ini dibutuhkan oleh {@code hibernate-tools-maven} agar bisa
 * terhubung ke database saat menjalankan {@code hbm2java}.
 * File akan dihapus oleh {@link io.github.mojo.GenerateMojo} setelah
 * proses selesai.</p>
 */
public class HibernatePropertiesGenerator {

    private HibernatePropertiesGenerator() {
    }

    /**
     * Generate file {@code hibernate.properties} ke path yang ditentukan.
     *
     * @param config     konfigurasi yang sudah di-load dari application properties/yaml
     * @param outputPath path tujuan, biasanya {@code hibernate.properties} di root project
     * @throws IOException jika gagal menulis file
     */
    public static void generate(GeneratorConfig config, Path outputPath) throws IOException {

        String content = "# Auto-generated by entity-repo-dbfirst-maven-plugin\n" +
                "# File ini dibuat sementara dan akan dihapus otomatis setelah proses selesai.\n\n" +
                "jakarta.persistence.jdbc.driver=" + config.getDbDriver() + "\n" +
                "jakarta.persistence.jdbc.url=" + config.getDbUrl() + "\n" +
                "jakarta.persistence.jdbc.user=" + config.getDbUser() + "\n" +
                "jakarta.persistence.jdbc.password=" + config.getDbPassword() + "\n";

        Files.writeString(outputPath, content);
    }
}
